# service port
server.port=4008

spring.datasource.url=jdbc:postgresql://localhost:5432/schedule_service_db
spring.datasource.username=postgres
spring.datasource.password=Atharva@10
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

admin.server.url=http://localhost:4006