# Spring boot application port
server.port=4006

spring.datasource.url=jdbc:postgresql://localhost:5432/admin_service_db
spring.datasource.username=postgres
spring.datasource.password=1522000@Me
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

