# Spring boot application port
server.port=4007

spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_service_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

# application.properties
slot.service.url=http://localhost:4008
patient.service.url=http://localhost:4000
admin.server.url=http://localhost:4006
availability.service.url=http://localhost:4008